name: build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu:
          - '20.04'
          - '22.04'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get runner version
        id: runner-version
        run: echo "::set-output name=version::$(sed -n 's/^ARG\s*RUNNER_VERSION=v\([0-9]\+\.[0-9]\+\.[0-9]\+\)$/\1/p' Dockerfile)"

      - name: Build image
        run: |
          docker build \
            --cache-from ghcr.io/${{ github.repository_owner }}/actions-runner:${{ steps.runner-version.outputs.version }}-ubuntu${{ matrix.ubuntu }} \
            --build-arg UBUNTU_VERSION=${{ matrix.ubuntu }} \
            -t ghcr.io/${{ github.repository_owner }}/actions-runner:latest .
      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          default_ubuntu_version=$(sed -n 's/^ARG\s*UBUNTU_VERSION=\([0-9]\+\.[0-9]\+\)$/\1/p' Dockerfile)
          docker tag \
            ghcr.io/${{ github.repository_owner }}/actions-runner:latest \
            ghcr.io/${{ github.repository_owner }}/actions-runner:${{ steps.runner-version.outputs.version }}-ubuntu${{ matrix.ubuntu }}
          docker push ghcr.io/${{ github.repository_owner }}/actions-runner:${{ steps.runner-version.outputs.version }}-ubuntu${{ matrix.ubuntu }}
          if [ ${default_ubuntu_version} = ${{ matrix.ubuntu }} ]
          then
            docker tag \
              ghcr.io/${{ github.repository_owner }}/actions-runner:latest \
              ghcr.io/${{ github.repository_owner }}/actions-runner:${{ steps.runner-version.outputs.version }}
            docker push ghcr.io/${{ github.repository_owner }}/actions-runner:${{ steps.runner-version.outputs.version }}
            docker push ghcr.io/${{ github.repository_owner }}/actions-runner:latest
          fi
